#!/bin/bash

# Atualizar pacotes
sudo apt-get update && sudo apt-get upgrade -y

# Instalar pacotes necessários
sudo apt-get install -y nfs-common

# Criar diretório para o ponto de montagem
sudo mkdir -p ${efs_mount_point}

# Montar o EFS usando o DNS fornecido pelo Terraform
sudo mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport ${file_system_id}:/ ${efs_mount_point}

# Garantir que o EFS seja montado após o reboot
echo "${file_system_id}:/ ${efs_mount_point} nfs4 defaults,_netdev 0 0" | sudo tee -a /etc/fstab
